"""Unit tests for DevOps lockfile generation."""

from __future__ import annotations

from pathlib import Path

from agent_builder.devops.lockfile import collect_import_roots, generate_requirements_lock


def test_collect_import_roots_detects_third_party(tmp_path: Path) -> None:
    (tmp_path / "main.py").write_text(
        "import flet\nimport json\nfrom pathlib import Path\n",
        encoding="utf-8",
    )
    roots = collect_import_roots(tmp_path)
    assert "flet" in roots
    assert "json" in roots
    assert "pathlib" in roots


def test_generate_requirements_lock_maps_flet(tmp_path: Path) -> None:
    (tmp_path / "app.py").write_text("import flet\n", encoding="utf-8")
    path = generate_requirements_lock(tmp_path)
    text = path.read_text(encoding="utf-8")
    assert path.name == "requirements.txt"
    assert "flet" in text
    assert "Generated by Agent Team Builder" in text
