"""Generate ``requirements.txt`` from project imports."""

from __future__ import annotations

import ast
import sys
from pathlib import Path

from agent_builder.validation.project_output import find_python_files

# Map import roots to PyPI distribution names.
_IMPORT_TO_PACKAGE: dict[str, str] = {
    "flet": "flet>=0.24.0",
    "PIL": "Pillow",
    "cv2": "opencv-python",
    "sklearn": "scikit-learn",
    "yaml": "PyYAML",
    "dotenv": "python-dotenv",
}

_BASE_REQUIREMENTS = ["# Generated by Agent Team Builder DevOps", ""]


def _stdlib_modules() -> frozenset[str]:
    names = getattr(sys, "stdlib_module_names", None)
    if names is not None:
        return frozenset(names)
    return frozenset(
        {
            "abc",
            "argparse",
            "ast",
            "asyncio",
            "collections",
            "dataclasses",
            "enum",
            "json",
            "logging",
            "os",
            "pathlib",
            "re",
            "sqlite3",
            "sys",
            "typing",
            "uuid",
        }
    )


def collect_import_roots(project_dir: Path) -> set[str]:
    """Collect top-level import names from Python files under *project_dir*."""
    roots: set[str] = set()
    for path in find_python_files(project_dir):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        except (SyntaxError, OSError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    roots.add(alias.name.split(".")[0])
            elif isinstance(node, ast.ImportFrom) and node.module:
                roots.add(node.module.split(".")[0])
    return roots


def generate_requirements_lock(project_dir: Path) -> Path:
    """Write ``requirements.txt`` from detected third-party imports."""
    stdlib = _stdlib_modules()
    roots = collect_import_roots(project_dir)
    lines = list(_BASE_REQUIREMENTS)

    packages: list[str] = []
    for root in sorted(roots):
        if root in stdlib or root.startswith("_"):
            continue
        spec = _IMPORT_TO_PACKAGE.get(root, root)
        if spec not in packages:
            packages.append(spec)

    if not packages:
        packages.append("# (no third-party imports detected)")

    lines.extend(packages)
    out = project_dir / "requirements.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out
