"""Generate PyInstaller ``.spec`` files for Flet/Python projects."""

from __future__ import annotations

from pathlib import Path


def generate_pyinstaller_spec(
    project_dir: Path,
    *,
    entry_script: str,
    project_name: str,
    onefile: bool = True,
) -> Path:
    """Write a minimal ``{project_name}.spec`` beside the entry script."""
    entry_rel = entry_script.replace("\\", "/")
    exe_name = _safe_exe_name(project_name)
    mode = "onefile" if onefile else "onedir"

    content = f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by Agent Team Builder DevOps ({mode})

block_cipher = None

a = Analysis(
    ["{entry_rel}"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="{exe_name}",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""
    spec_path = project_dir / f"{exe_name}.spec"
    spec_path.write_text(content, encoding="utf-8")
    return spec_path


def _safe_exe_name(project_name: str) -> str:
    cleaned = "".join(c if c.isalnum() or c in "-_" else "_" for c in project_name)
    return cleaned.strip("_") or "app"
